---
- name: Apply
  # It takes the hosts that is under the hosts section from inventory.yml
  #   - Used for variables like "inventory_hostname"
  hosts: wave2_cluster
  strategy: free
  gather_facts: false

  tasks:
  - name: Render tfvars for each module
    ansible.builtin.include_role:
      name: tfvars

  - name: Apply All
    include_role:
      name: apply
    vars:
      target_dir: "{{ module[inventory_hostname].dir }}"
      plan_file: "{{ inventory_hostname }}.tfplan"
      apply_destroy: false
