name: Static Analysis

on:
  push:
    branches: [main]
    paths:
      - "**/*.tf"
      - "**/*.tftpl"
      - "**/*.tmpl"
      - "**/*.sh"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.env"
      - "**/*.tfvars"
      - ".tflint.hcl"
      - ".checkov.yaml"
      - ".github/workflows/static-analysis.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.tf"
      - "**/*.tftpl"
      - "**/*.tmpl"
      - "**/*.sh"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.env"
      - "**/*.tfvars"
      - ".tflint.hcl"
      - ".checkov.yaml"
      - ".github/workflows/static-analysis.yml"

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.11.2"

      - name: Format check
        run: tofu fmt -check -recursive

      - name: Validate k3s_cluster
        working-directory: k3s_cluster
        run: |
          tofu init -backend=false
          tofu validate
